var ZlibModule=(()=>{var _scriptName=typeof document!="undefined"?document.currentScript?.src:undefined;return async function(moduleArg={}){var moduleRtn;var b=moduleArg,aa="object"==typeof window,n="undefined"!=typeof WorkerGlobalScope;n&&(_scriptName=self.location.href);var q="",r,t;
if(aa||n){try{q=(new URL(".",_scriptName)).href}catch{}n&&(t=a=>{var c=new XMLHttpRequest;c.open("GET",a,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)});r=async a=>{if(w(a))return new Promise((d,e)=>{var g=new XMLHttpRequest;g.open("GET",a,!0);g.responseType="arraybuffer";g.onload=()=>{200==g.status||0==g.status&&g.response?d(g.response):e(g.status)};g.onerror=e;g.send(null)});var c=await fetch(a,{credentials:"same-origin"});if(c.ok)return c.arrayBuffer();throw Error(c.status+
" : "+c.url);}}var x=console.error.bind(console),y,z=!1,A,w=a=>a.startsWith("file://"),B,C,D,G,H,I=!1;function J(){var a=D.buffer;b.HEAP8=G=new Int8Array(a);new Int16Array(a);b.HEAPU8=H=new Uint8Array(a);new Uint16Array(a);b.HEAP32=new Int32Array(a);b.HEAPU32=new Uint32Array(a);new Float32Array(a);new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a)}var K=0,L=null;
function M(a){b.onAbort?.(a);a="Aborted("+a+")";x(a);z=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");C?.(a);throw a;}var N;async function ba(a){if(!y)try{var c=await r(a);return new Uint8Array(c)}catch{}if(a==N&&y)a=new Uint8Array(y);else if(t)a=t(a);else throw"both async and sync fetching of the wasm failed";return a}
async function ca(a,c){try{var d=await ba(a);return await WebAssembly.instantiate(d,c)}catch(e){x(`failed to asynchronously prepare wasm: ${e}`),M(e)}}async function da(a){var c=N;if(!y&&!w(c))try{var d=fetch(c,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(d,a)}catch(e){x(`wasm streaming compile failed: ${e}`),x("falling back to ArrayBuffer instantiation")}return ca(c,a)}
class O{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var P=a=>{for(;0<a.length;)a.shift()(b)},Q=[],ea=[],ha=()=>{var a=b.preRun.shift();ea.push(a)},R=!0,S=0,T={},ia=a=>{if(!(a instanceof O||"unwind"==a))throw a;},ja=a=>{A=a;R||0<S||(b.onExit?.(a),z=!0);throw new O(a);},ka=a=>{if(!z)try{if(a(),!(R||0<S))try{A=a=A,ja(a)}catch(c){ia(c)}}catch(c){ia(c)}},la=new TextDecoder,ma=a=>{const c=a.length;return[c%128|128,c>>7,...a]},na={i:127,p:127,j:126,f:125,d:124,e:111},oa=a=>ma(Array.from(a,c=>na[c])),U,V,W=[];b.noExitRuntime&&(R=b.noExitRuntime);
b.printErr&&(x=b.printErr);b.wasmBinary&&(y=b.wasmBinary);
b.ccall=(a,c,d,e)=>{var g={string:h=>{var k=0;if(null!==h&&void 0!==h&&0!==h){for(var f=k=0;f<h.length;++f){var l=h.charCodeAt(f);127>=l?k++:2047>=l?k+=2:55296<=l&&57343>=l?(k+=4,++f):k+=3}var p=k+1;k=X(p);l=H;f=k>>>0;if(0<p){p=f+p-1;for(var E=0;E<h.length;++E){var m=h.codePointAt(E);if(127>=m){if(f>=p)break;l[f++>>>0]=m}else if(2047>=m){if(f+1>=p)break;l[f++>>>0]=192|m>>6;l[f++>>>0]=128|m&63}else if(65535>=m){if(f+2>=p)break;l[f++>>>0]=224|m>>12;l[f++>>>0]=128|m>>6&63;l[f++>>>0]=128|m&63}else{if(f+
3>=p)break;l[f++>>>0]=240|m>>18;l[f++>>>0]=128|m>>12&63;l[f++>>>0]=128|m>>6&63;l[f++>>>0]=128|m&63;E++}}l[f>>>0]=0}}return k},array:h=>{var k=X(h.length);G.set(h,k>>>0);return k}};a=b["_"+a];var u=[],F=0;if(e)for(var v=0;v<e.length;v++){var fa=g[d[v]];fa?(0===F&&(F=pa()),u[v]=fa(e[v])):u[v]=e[v]}d=a(...u);return d=function(h){0!==F&&qa(F);if("string"===c)if(h>>>=0){for(var k=h,f=H,l=k+void 0;f[k]&&!(k>=l);)++k;h=la.decode(H.subarray(h>>>0,k>>>0))}else h="";else h="boolean"===c?!!h:h;return h}(d)};
b.addFunction=(a,c)=>{if(!V){V=new WeakMap;var d=U.length;if(V)for(var e=0;e<0+d;e++){var g=U.get(e);g&&V.set(g,e)}}if(d=V.get(a)||0)return d;d=W.length?W.pop():U.grow(1);try{U.set(d,a)}catch(u){if(!(u instanceof TypeError))throw u;c=Uint8Array.of(0,97,115,109,1,0,0,0,1,...ma([1,96,...oa(c.slice(1)),...oa("v"===c[0]?"":c[0])]),2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);c=new WebAssembly.Module(c);c=(new WebAssembly.Instance(c,{e:{f:a}})).exports.f;U.set(d,c)}V.set(a,d);return d};
b.removeFunction=a=>{V.delete(U.get(a));U.set(a,null);W.push(a)};
var ra,qa,X,pa,sa={c:()=>M(""),b:()=>{R=!1;S=0},d:(a,c)=>{T[a]&&(clearTimeout(T[a].id),delete T[a]);if(!c)return 0;var d=setTimeout(()=>{delete T[a];ka(()=>ra(a,performance.now()))},c);T[a]={id:d,A:c};return 0},e:function(a){a>>>=0;var c=H.length;if(4294901760<a)return!1;for(var d=1;4>=d;d*=2){var e=c*(1+.2/d);e=Math.min(e,a+100663296);a:{e=(Math.min(4294901760,65536*Math.ceil(Math.max(a,e)/65536))-D.buffer.byteLength+65535)/65536|0;try{D.grow(e);J();var g=1;break a}catch(u){}g=void 0}if(g)return!0}return!1},
a:ja},Y=await (async function(){function a(d){Y=d.exports;Y=ta();D=Y.f;J();U=Y.t;d=Y;b._deflate=d.h;b._deflateEnd=d.i;b._deflateInit2_=d.j;b._inflateInit2_=d.k;b._inflate=d.l;b._inflateEnd=d.m;b._malloc=d.n;b._free=d.o;b._inflateBack9Init_=d.p;b._inflateBack9=d.q;b._inflateBack9End=d.r;ra=d.s;qa=d.u;X=d.v;pa=d.w;K--;b.monitorRunDependencies?.(K);0==K&&L&&(d=L,L=null,d());return Y}K++;b.monitorRunDependencies?.(K);var c={a:sa};if(b.instantiateWasm)return new Promise(d=>{b.instantiateWasm(c,
(e,g)=>{d(a(e,g))})});N??=b.locateFile?b.locateFile("zlib-module.wasm",q):q+"zlib-module.wasm";return a((await da(c)).instance)}());function ta(){var a=Y;a=Object.assign({},a);var c=d=>e=>d(e)>>>0;a.n=c(a.n);a.v=c(a.v);a.w=(d=>()=>d()>>>0)(a.w);return a}
function Z(){function a(){b.calledRun=!0;if(!z){I=!0;Y.g();B?.(b);b.onRuntimeInitialized?.();if(b.postRun)for("function"==typeof b.postRun&&(b.postRun=[b.postRun]);b.postRun.length;){var c=b.postRun.shift();Q.push(c)}P(Q)}}if(0<K)L=Z;else{if(b.preRun)for("function"==typeof b.preRun&&(b.preRun=[b.preRun]);b.preRun.length;)ha();P(ea);0<K?L=Z:b.setStatus?(b.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>b.setStatus(""),1);a()},1)):a()}}
if(b.preInit)for("function"==typeof b.preInit&&(b.preInit=[b.preInit]);0<b.preInit.length;)b.preInit.shift()();Z();I?moduleRtn=b:moduleRtn=new Promise((a,c)=>{B=a;C=c});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=ZlibModule;module.exports.default=ZlibModule}else if(typeof define==="function"&&define["amd"])define([],()=>ZlibModule);
